rutube:
  features:
    interaction_features: [
      "viewer_uid",
      "rutube_video_id",
      "total_watchtime",
      "timestamp",
      "ua_device_type",
      "ua_os",
      "detailed_view",
      "category",
      "detailed_view_embedding",
      "detailed_view_embedding_list",
      "category_embedding",
      "category_embedding_list"
    ]
    user_features: [
      "viewer_uid",
      "age",
      "sex",
      "region"
    ]
    item_features: [
      "rutube_video_id",
      "title",
      "category",
      "duration",
      "author_id"
    ]
    numerical_features: [
      "total_watchtime",
      "timestamp",
      "duration",
      "age",
      "hour_sin",
      "hour_cos",
      "detailed_view_embedding",
      "detailed_view_embedding_list",
      "category_embedding",
      "category_embedding_list"
    ]
    categorical_features: [
      "sex",
      "region",
      "ua_device_type",
      "ua_os",
      "category"
    ]

  field_mapping:
    USER_ID_FIELD: "viewer_uid"
    ITEM_ID_FIELD: "rutube_video_id"
    RATING_FIELD: "total_watchtime"
    TIME_FIELD: "timestamp"
    TEXT_FIELDS: ["detailed_view", "category"]

lastfm:
  features:
    interaction_features: [
      "user_id",
      "artist_id",
      "timestamp",
      "plays",
      "artist_name",
      "artist_name_embedding",
      "artist_name_embedding_list"
    ]
    user_features: [
      "user_id",
      "age",
      "gender",
      "country"
    ]
    item_features: [
      "artist_id",
      "artist_name"
    ]
    numerical_features: [
      "plays",
      "age",
      "artist_name_embedding",
      "artist_name_embedding_list"
    ]
    categorical_features: [
      "gender",
      "country"
    ]

  field_mapping:
    USER_ID_FIELD: "user_id"
    ITEM_ID_FIELD: "artist_id"
    RATING_FIELD: "plays"
    TIME_FIELD: "timestamp"
    TEXT_FIELDS: ["artist_name"] 