rutube:
  features:
    interaction_features: [
      "viewer_uid",
      "rutube_video_id",
      "total_watchtime",
      "timestamp"
    ]
    user_features: ["viewer_uid"]
    item_features: ["rutube_video_id"]
    numerical_features: ["total_watchtime", "timestamp"]

  field_mapping:
    USER_ID_FIELD: "viewer_uid"
    ITEM_ID_FIELD: "rutube_video_id"
    RATING_FIELD: "total_watchtime"
    TIME_FIELD: "timestamp"

lastfm:
  features:
    interaction_features: [
      "user_id",
      "artist_id",
      "timestamp",
      "plays",
    ]
    user_features: ["user_id"]
    item_features: ["artist_id"]
    numerical_features: ["plays"]

  field_mapping:
    USER_ID_FIELD: "user_id"
    ITEM_ID_FIELD: "artist_id"
    RATING_FIELD: "plays"
    TIME_FIELD: "timestamp" 

name: "id_only"