model:
  text_model_name: "intfloat/multilingual-e5-large"
  id_embed_dim: 32
  text_embed_dim: 1024

data:
  max_length: 128
  batch_size: 32

training:
  epochs: 10
  batch_size: 32
  learning_rate: 0.001
  lambda_rec: 0.5
  checkpoint_dir: "checkpoints"  # Базовая директория для чекпоинтов
  save_strategy: "epoch"         # Когда сохранять: "epoch" или "best"
  save_steps: 1                  # Сохранять каждые N эпох
  save_total_limit: 3           # Максимальное количество сохраняемых чекпоинтов 

inference:
  model_path: "checkpoints/model_epoch_10"  # Путь к директории с моделью
  batch_size: 32
  num_examples: 5  # Количество примеров для показа
  top_k: 10       # Количество рекомендаций для каждого пользователя 