model:
  text_model_name: "intfloat/multilingual-e5-large"
  id_embed_dim: 32
  text_embed_dim: 1024

data:
  max_length: 128
  batch_size: 32

training:
  epochs: 1
  learning_rate: 5e-5
  lambda_rec: 0.2
  validation_size: 0.1
  random_seed: 42
  checkpoint_dir: "checkpoints"  # Базовая директория для чекпоинтов
  save_strategy: "epoch"         # Когда сохранять: "epoch" или "best"
  save_steps: 1                  # Сохранять каждые N эпох
  save_total_limit: 3           # Максимальное количество сохраняемых чекпоинтов 

inference:
  embeddings_path: "./data/item_embeddings.npy"
  model_path: "intfloat/multilingual-e5-large"  # Путь к директории с моделью
  num_examples: 5  # Количество примеров для показа
  top_k: 10       # Количество рекомендаций для каждого пользователя 